name: Generate and Post to X

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate-and-post:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body || github.event.issue.body, '@claude-generate')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate AI message
      uses: anthropics/claude-code-action@beta
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        trigger_phrase: "@claude-generate"
        direct_prompt: |
          src/index.jsのメッセージを「今日は何の日」に関連したAI生成メッセージに変更してください。
          【GitHub Actions + Claude Code AI生成】プレフィックス付きで創造的な内容にしてください。
    
    - name: Post to X
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: npm run post