name: Claude Message Generator

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body || github.event.issue.body, '@claude-generate')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate AI message
      uses: anthropics/claude-code-action@beta
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        trigger_phrase: "@claude-generate"
        direct_prompt: |
          src/index.jsのメッセージを「今日は何の日」に関連したAI生成メッセージに変更してください。
          【GitHub Actions + Claude Code生成】プレフィックス付きで創造的な内容にしてください。