name: Post to X (Twitter)

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - run: npm ci
    
    - name: Generate AI message
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        prompt: |
          src/index.jsのメッセージを「今日は何の日」に関連したAI生成メッセージに変更してください。
          【GitHub Actions + Claude Code AI生成】プレフィックス付きで創造的な内容にしてください。
    
    - name: Post to X
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: npm run post